# Sesssion 14

1. Understanding What's NumPy
2. Build Array
3. Subsetting NumPy
4. 2D NumPy
5. Run NumPy for Statistics

In [1]:
# import numpy library 
import numpy as np

### Array vs List
1. Array can contain more than one dimensions
2. Array can only contain element with the same type
3. Mathematics operation can apply

In [2]:
# create list and numpy array
sebuah_list = [1, 2, 3, 4, 5, 6]
sebuah_array = np.array([1, 2, 3, 4, 5, 6])

# create list matrix and numpy array 
sebuah_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_matrix = np.array(sebuah_matrix)

In [3]:
print(sebuah_list * 2)
print(sebuah_array * 2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 2  4  6  8 10 12]


### Build in Method

#### List of zeros and ones

In [4]:
np.zeros((2, 5))

np.ones((2, 5), dtype='int64')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

#### Range

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(5, 100, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### Array with an evenly divided range

In [8]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.linspace(0, 100, 5, dtype='int64')

array([  0,  25,  50,  75, 100], dtype=int64)

#### Array containing a sample

In [10]:
np.random.randn(2)

array([0.8910878 , 0.58595731])

In [11]:
np.random.randn(2, 3)

array([[ 0.30078798, -1.59956956,  0.77369382],
       [-0.70914272,  0.18951748,  0.89069264]])

In [12]:
np.random.randint(2, 100, 7)

array([64, 26, 87, 49, 49, 96, 15])

In [13]:
np.random.randint(2, 100, [3, 4])  # low, hieght, size

array([[56, 94, 50, 66],
       [88, 28, 24, 89],
       [23, 12, 90, 52]])

### Array Attribute

In [14]:
# sum, min, max, mean
array1 = np.array([1, 2, 3, 4, 5, 6])
print(array1.sum())
print(array1.min())
print(array1.max())
print(array1.mean())

21
1
6
3.5


In [15]:
a1 = np.random.randint(1, 21, [4, 5])
a1

array([[ 6,  2,  2,  1, 11],
       [19,  6, 15,  7,  7],
       [20, 13,  2, 17, 18],
       [ 8,  6,  8, 14, 10]])

In [16]:
a1.min(axis=0)

array([6, 2, 2, 1, 7])

In [17]:
a1.min(axis=1)

array([1, 6, 2, 6])

In [18]:
# shape, size, reshape
arr = np.random.randint(1, 10, [3, 4])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.reshape(4, 3))

[[4 4 8 9]
 [2 5 3 8]
 [6 4 8 9]]
(3, 4)
12
[[4 4 8]
 [9 2 5]
 [3 8 6]
 [4 8 9]]


### Indexing and Slicing

In [19]:
sebuah_array = np.arange(20)
sebuah_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
sebuah_array[:6]

array([0, 1, 2, 3, 4, 5])

In [21]:
sebuah_array[5:14]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [22]:
sebuah_array[(sebuah_array%2 == 0) & (sebuah_array > 10)]

array([12, 14, 16, 18])

### Create Array from Existing Data

In [23]:
a1 = np.array([[1, 1], 
             [2, 2]])

a2 = np.array([[3, 3], 
             [4, 4]])

In [24]:
np.vstack((a1, a2)) # jumlah kolom harus sama

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [25]:
np.hstack((a1, a2)) # jumlah baris harus sama

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [26]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [27]:
np.hsplit(x, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

### Basic Array Operations

In [28]:
a1 = np.arange(1, 11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
a1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

### Exercise

In [31]:
# 1. Buat array dengan output seperti ini
np.random.randint(5, 6, 10, dtype='int64')

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [32]:
np.array([range(i, i+3) for i in [1, 3, 5]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [33]:
np.array([[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [34]:
# 3. 
a1 =np.arange(1, 10).reshape(3, 3)
a1[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [35]:
def create_matrix(start=1):
    output = np.array([range(i, i+3) for i in [start, start+2, start+4]])
    return output

In [36]:
create_matrix()

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [37]:
create_matrix(3)

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])