# Matrix

In [1]:
import numpy as np

In [2]:
vector_row =  np.array([1, -5, 3, 2,4])
vector_column = np.array ([[1],
                           [2],
                           [3],
                           [4]])
vector_row.shape

(5,)

In [3]:
vector_column.shape

(4, 1)

In [4]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v - 2*w+4*u
print(x)

[[-8 -1  4]]


In [5]:
x.shape

(1, 3)

In [6]:
# Definisi Matrix
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
P

array([[1, 7],
       [2, 3],
       [5, 0]])

In [7]:
P.shape

(3, 2)

In [8]:
Q

array([[2, 6, 3, 1],
       [1, 2, 3, 4]])

In [9]:
Q.shape

(2, 4)

# Matrix Multiplication

In [10]:
P * Q 

ValueError: operands could not be broadcast together with shapes (3,2) (2,4) 

In [11]:
np.dot(P, Q)

array([[ 9, 20, 24, 29],
       [ 7, 18, 15, 14],
       [10, 30, 15,  5]])

In [12]:
np.dot(Q, P)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

# Matrix Determinant

In [13]:
from numpy.linalg import det

M = np.array([[0,2,1,3],
              [3,2,8,1],
              [1,0,0,3],
              [0,3,2,1]])
print('M:\n', M)
print('Determinant: %.1f'%det(M))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0


# Identity Matrix

In [14]:
I = np.eye(4) #default parameter float
print('I:\n', I)
print('M*I:\n', np.dot(M,I))

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [15]:
I = np.eye(4, dtype = int) #change to int
print('I:\n', I)
print('M*I:\n', np.dot(M,I))

I:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
M*I:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]


# Inverse Matrix

In [16]:
from numpy.linalg import inv

print('Inv M:\n', inv(M))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [17]:
np.dot(M, inv(M)) #reverse order, different result

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16,
        -4.44089210e-16],
       [ 2.22044605e-16,  5.55111512e-17,  1.00000000e+00,
        -4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [18]:
np.dot(inv(M), M)

array([[ 1.00000000e+00, -4.44089210e-16,  2.22044605e-16,
         1.11022302e-15],
       [ 5.55111512e-17,  1.00000000e+00,  2.22044605e-16,
         5.55111512e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -8.32667268e-16],
       [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16,
         1.00000000e+00]])

In [19]:
np.dot(inv(M), M).round()

array([[ 1., -0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0., -0.,  1.]])

# Matrix without inverse

In [20]:
S = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(S):\n', det(S))

det(S):
 0.0


The above result shows that it is a singular matrix

In [21]:
inv(S)

LinAlgError: Singular matrix

Solve:
\begin{eqnarray*}
4x_1 + 3x_2 - 5x_3 &=& 2 \\
-2x_1 + 4x_2 + 5x_3 &=& 5 \\
8x_1 + 8x_2 &=& -3 \\
\end{eqnarray*}

In [22]:
A = np.array([[4, 3,-5],
             [-2,4,5],
             [8,8,0]])
y = np.array([[2],
              [5],
              [-3]]) #vector output


In [23]:
x = np.linalg.solve(A,y) #Solve the problem
print(x)

[[-1.925]
 [ 1.55 ]
 [-1.01 ]]


In [24]:
A_inv = inv(A) #Solve the problem using matrix inverse

x = np.dot(A_inv, y)
print(x)

[[-1.925]
 [ 1.55 ]
 [-1.01 ]]


## Example: Massey Matrix for English Premier League (EPL) Rank of Last Season

According to https://pena.lt/y/2014/12/04/massey-ratings-for-football-part-two/ <br />
"Massey Ratings
The idea behind Massey Ratings is that they rate teams such that the difference between any two teams is equal to the expected margin of victory between them. For example, if a team rated -1.0 played a team rated +1.0 then we’d expect the average goal difference between them to be two goals.

Since Massey Ratings look at goal difference rather than goals scored or conceded they account for a team’s overall strength and combine both their attack and defence strengths together into a single value. This means with a bit of mathematics we should be able to decompose a Massey Rating to split out these two constituent parts."

In [25]:
import pandas as pd

In [26]:
df = pd.read_html('https://www.anfield-online.co.uk/stats/2020-21/premier-league-table-2020-21.html')
df

[    Pos    H    A  Pts v                     Team  Pl   W   D   L   F  A.1  \
 0     1  1-4  1-1    1.0          Manchester City  38  27   5   6  83   32   
 1     2  0-0  4-2    4.0        Manchester United  38  21  11   6  73   44   
 2     3  NaN  NaN    NaN                Liverpool  38  20   9   9  68   42   
 3     4  0-1  2-0    3.0                  Chelsea  38  19  10   9  58   36   
 4     5  3-0  1-3    3.0           Leicester City  38  20   6  12  68   50   
 5     6  2-1  3-1    6.0          West Ham United  38  19   8  11  62   47   
 6     7  2-1  3-1    6.0        Tottenham Hotspur  38  18   8  12  68   45   
 7     8  3-1  3-0    6.0                  Arsenal  38  18   7  13  55   39   
 8     9  4-3  1-1    4.0             Leeds United  38  18   5  15  62   54   
 9    10  0-2  2-2    1.0                  Everton  38  17   8  13  47   48   
 10   11  2-1  2-7    3.0              Aston Villa  38  16   7  15  55   46   
 11   12  1-1  0-0    2.0         Newcastle United  

In [27]:
df[0]

Pos    H    A  Pts v                     Team  Pl   W   D   L   F  A.1  \
0     1  1-4  1-1    1.0          Manchester City  38  27   5   6  83   32   
1     2  0-0  4-2    4.0        Manchester United  38  21  11   6  73   44   
2     3  NaN  NaN    NaN                Liverpool  38  20   9   9  68   42   
3     4  0-1  2-0    3.0                  Chelsea  38  19  10   9  58   36   
4     5  3-0  1-3    3.0           Leicester City  38  20   6  12  68   50   
5     6  2-1  3-1    6.0          West Ham United  38  19   8  11  62   47   
6     7  2-1  3-1    6.0        Tottenham Hotspur  38  18   8  12  68   45   
7     8  3-1  3-0    6.0                  Arsenal  38  18   7  13  55   39   
8     9  4-3  1-1    4.0             Leeds United  38  18   5  15  62   54   
9    10  0-2  2-2    1.0                  Everton  38  17   8  13  47   48   
10   11  2-1  2-7    3.0              Aston Villa  38  16   7  15  55   46   
11   12  1-1  0-0    2.0         Newcastle United  38  12   9  17  46   62   
12   13  4-0  1-0    6.0  Wolverhampton Wanderers  38  12   9  17  36   52   
13   14  2-0  7-0    6.0           Crystal Palace  38  12   8  18  41   66   
14   15  2-0  0-1    3.0              Southampton  38  12   7  19  47   68   
15   16  0-1  1-1    1.0   Brighton & Hove Albion  38   9  14  15  40   46   
16   17  0-1  3-0    3.0                  Burnley  38  10   9  19  33   55   
17   18  0-1  1-1    1.0                   Fulham  38   5  13  20  27   53   
18   19  1-1  2-1    4.0     West Bromwich Albion  38   5  11  22  35   76   
19   20  2-1  2-0    6.0         Sheffield United  38   7   2  29  20   63   

    GD  Pts  
0   51   86  
1   29   74  
2   26   69  
3   22   67  
4   18   66  
5   15   65  
6   23   62  
7   16   61  
8    8   59  
9   -1   59  
10   9   55  
11 -16   45  
12 -16   45  
13 -25   44  
14 -21   43  
15  -6   41  
16 -22   39  
17 -26   28  
18 -41   26  
19 -43   23

In [28]:
team = df[0]['Team']
team

0             Manchester City
1           Manchester United
2                   Liverpool
3                     Chelsea
4              Leicester City
5             West Ham United
6           Tottenham Hotspur
7                     Arsenal
8                Leeds United
9                     Everton
10                Aston Villa
11           Newcastle United
12    Wolverhampton Wanderers
13             Crystal Palace
14                Southampton
15     Brighton & Hove Albion
16                    Burnley
17                     Fulham
18       West Bromwich Albion
19           Sheffield United
Name: Team, dtype: object

In [29]:
GD = df[0]['GD']
GD

0     51
1     29
2     26
3     22
4     18
5     15
6     23
7     16
8      8
9     -1
10     9
11   -16
12   -16
13   -25
14   -21
15    -6
16   -22
17   -26
18   -41
19   -43
Name: GD, dtype: int64

In [30]:
massey_epl = np.array([[38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38, -2],
[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 38]])


In [31]:
x = np.linalg.solve(massey_epl, GD)
print(x)

[ 1.59675325  1.04675325  0.97175325  0.87175325  0.77175325  0.69675325
  0.89675325  0.72175325  0.52175325  0.29675325  0.54675325 -0.07824675
 -0.07824675 -0.30324675 -0.20324675  0.17175325 -0.22824675 -0.32824675
 -0.70324675 -0.75324675]


In [32]:
pd.DataFrame(np.transpose([team,x]))

0          1
0           Manchester City    1.59675
1         Manchester United    1.04675
2                 Liverpool   0.971753
3                   Chelsea   0.871753
4            Leicester City   0.771753
5           West Ham United   0.696753
6         Tottenham Hotspur   0.896753
7                   Arsenal   0.721753
8              Leeds United   0.521753
9                   Everton   0.296753
10              Aston Villa   0.546753
11         Newcastle United -0.0782468
12  Wolverhampton Wanderers -0.0782468
13           Crystal Palace  -0.303247
14              Southampton  -0.203247
15   Brighton & Hove Albion   0.171753
16                  Burnley  -0.228247
17                   Fulham  -0.328247
18     West Bromwich Albion  -0.703247
19         Sheffield United  -0.753247

Ini adalah ranking aslinya, kolom (0) kanan hasil rating berdasarkan Messay

In [33]:
pd.DataFrame(np.transpose([team,x])).sort_values(1, ascending = False)

0          1
0           Manchester City    1.59675
1         Manchester United    1.04675
2                 Liverpool   0.971753
6         Tottenham Hotspur   0.896753
3                   Chelsea   0.871753
4            Leicester City   0.771753
7                   Arsenal   0.721753
5           West Ham United   0.696753
10              Aston Villa   0.546753
8              Leeds United   0.521753
9                   Everton   0.296753
15   Brighton & Hove Albion   0.171753
11         Newcastle United -0.0782468
12  Wolverhampton Wanderers -0.0782468
14              Southampton  -0.203247
16                  Burnley  -0.228247
13           Crystal Palace  -0.303247
17                   Fulham  -0.328247
18     West Bromwich Albion  -0.703247
19         Sheffield United  -0.753247

# Eigenvalue and Eigenvectors

A = \begin{bmatrix}
0 & 2\\
2 & 3\\
\end{bmatrix}

In [34]:
from numpy.linalg import eig
a = np.array([[0, 2],
             [2, 3]])
w,v=eig(a)
print('E-value: ', w)
print('E-vector', v)


E-value:  [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


*Av = lambda * v ?*

In [35]:
np.dot(a,v[:,0]) 

array([ 0.89442719, -0.4472136 ])

Coba kalikan matrix a dengan eigenvector pertama (menggunakan semua baris dan kolom pertama)

In [36]:
np.dot(w[0],v[:0])

array([], shape=(0, 2), dtype=float64)

Kalikan eigenvalue pertama dengan eigenvector pertama. <br /> Memproyeksikan atau merepresentasikan berbagai macam vector dengan eigenvalue dan eigenvector tersebut

### 3 x 3 Matrix

A = \begin{bmatrix}
2 & 2 & 4\\
1 & 3 & 5\\
2 & 3 & 4\\
\end{bmatrix}

In [37]:
from numpy.linalg import eig
a = np.array([[2, 2,4],
             [1, 3, 5],
             [2, 3, 4]])
w,v=eig(a)
print('E-value: ', w)
print('E-vector', v)

E-value:  [ 8.80916362  0.92620912 -0.73537273]
E-vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
